name: Build and Deploy inLink backend

on:
  push:
    branches:
      - main

jobs:
  build-depoy:
    name: Build inLink backend app
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Steup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Build app without tests(db connection, unit testing)
        run: ./gradlew clean build -x test